"""
Retail Analytics Dashboard — ETL Script
========================================

Reads the Superstore CSV, normalizes it into 5 tables (regions, customers,
products, orders, order_items), and either:
  (a) writes INSERT statements to 02_data.sql  (default), OR
  (b) loads directly into MySQL                 (with --load flag)

Usage
-----
    # Option A — generate SQL file (no MySQL connection needed)
    python 02_etl.py --csv train.csv --out 02_data.sql

    # Option B — load directly into MySQL
    python 02_etl.py --csv train.csv --load \\
        --host localhost --user root --password YOUR_PW \\
        --database retail_analytics

Notes
-----
  - Run 01_schema.sql first (it creates the database and tables).
  - If a single product_id has multiple names in the source, we keep the
    most frequent one.
  - Dates in the source are DD/MM/YYYY. We parse with dayfirst=True.
"""

import argparse
import sys
from pathlib import Path

import pandas as pd


REGION_IDS = {'Central': 1, 'East': 2, 'South': 3, 'West': 4}


def load_and_clean(csv_path: Path) -> pd.DataFrame:
    df = pd.read_csv(csv_path)
    df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)
    df['Ship Date'] = pd.to_datetime(df['Ship Date'], dayfirst=True)
    # Postal code -> string, preserve leading zeros; NaN -> None
    df['Postal Code'] = df['Postal Code'].apply(
        lambda x: None if pd.isna(x) else str(int(x)).zfill(5)
    )
    return df


def build_customers(df: pd.DataFrame) -> pd.DataFrame:
    # Each customer has a unique (Name, Segment) per Customer ID (verified).
    return (
        df[['Customer ID', 'Customer Name', 'Segment']]
        .drop_duplicates(subset='Customer ID')
        .sort_values('Customer ID')
        .reset_index(drop=True)
    )


def build_products(df: pd.DataFrame) -> pd.DataFrame:
    # Some product IDs have >1 name variant in the source; take the most
    # frequent. Category / Sub-Category are consistent per product ID.
    most_common_name = (
        df.groupby('Product ID')['Product Name']
        .agg(lambda s: s.value_counts().index[0])
        .rename('Product Name')
    )
    static = (
        df[['Product ID', 'Category', 'Sub-Category']]
        .drop_duplicates(subset='Product ID')
        .set_index('Product ID')
    )
    return (
        static.join(most_common_name)
        .reset_index()
        [['Product ID', 'Product Name', 'Category', 'Sub-Category']]
        .sort_values('Product ID')
        .reset_index(drop=True)
    )


def build_orders(df: pd.DataFrame) -> pd.DataFrame:
    # Geography is consistent per Order ID (verified).
    orders = (
        df[['Order ID', 'Customer ID', 'Order Date', 'Ship Date', 'Ship Mode',
            'Country', 'City', 'State', 'Postal Code', 'Region']]
        .drop_duplicates(subset='Order ID')
        .sort_values('Order ID')
        .reset_index(drop=True)
    )
    orders['region_id'] = orders['Region'].map(REGION_IDS)
    return orders


def build_order_items(df: pd.DataFrame) -> pd.DataFrame:
    return (
        df[['Row ID', 'Order ID', 'Product ID', 'Sales']]
        .sort_values('Row ID')
        .reset_index(drop=True)
    )


def sql_escape(val) -> str:
    """MySQL-safe string literal."""
    if val is None or (isinstance(val, float) and pd.isna(val)):
        return 'NULL'
    if isinstance(val, (int, float)):
        return str(val)
    # str: escape single quotes and backslashes
    return "'" + str(val).replace('\\', '\\\\').replace("'", "''") + "'"


def batched_insert(table: str, cols: list, rows: list, batch_size: int = 500) -> str:
    """Build INSERT statements batched for speed."""
    if not rows:
        return ''
    col_list = ', '.join(f'`{c}`' for c in cols)
    out = []
    for i in range(0, len(rows), batch_size):
        chunk = rows[i:i + batch_size]
        values = ',\n    '.join(
            '(' + ', '.join(sql_escape(v) for v in row) + ')'
            for row in chunk
        )
        out.append(f'INSERT INTO `{table}` ({col_list}) VALUES\n    {values};\n')
    return '\n'.join(out)


def write_sql_file(customers, products, orders, order_items, out_path: Path):
    with out_path.open('w', encoding='utf-8') as f:
        f.write('-- Generated by 02_etl.py — data load for retail_analytics\n')
        f.write('USE retail_analytics;\n\n')
        f.write('-- Disable FK checks during load for speed\n')
        f.write('SET FOREIGN_KEY_CHECKS = 0;\n\n')

        # customers
        f.write('-- customers\n')
        f.write(batched_insert(
            'customers',
            ['customer_id', 'customer_name', 'segment'],
            customers[['Customer ID', 'Customer Name', 'Segment']].values.tolist(),
        ))
        f.write('\n')

        # products
        f.write('-- products\n')
        f.write(batched_insert(
            'products',
            ['product_id', 'product_name', 'category', 'sub_category'],
            products[['Product ID', 'Product Name', 'Category', 'Sub-Category']].values.tolist(),
        ))
        f.write('\n')

        # orders
        f.write('-- orders\n')
        orders_rows = [
            [r['Order ID'], r['Customer ID'],
             r['Order Date'].strftime('%Y-%m-%d'),
             r['Ship Date'].strftime('%Y-%m-%d'),
             r['Ship Mode'],
             r['Country'], r['City'], r['State'],
             r['Postal Code'] if r['Postal Code'] is not None else None,
             int(r['region_id'])]
            for _, r in orders.iterrows()
        ]
        f.write(batched_insert(
            'orders',
            ['order_id', 'customer_id', 'order_date', 'ship_date', 'ship_mode',
             'country', 'city', 'state', 'postal_code', 'region_id'],
            orders_rows,
        ))
        f.write('\n')

        # order_items
        f.write('-- order_items\n')
        items_rows = [
            [int(r['Row ID']), r['Order ID'], r['Product ID'], float(r['Sales'])]
            for _, r in order_items.iterrows()
        ]
        f.write(batched_insert(
            'order_items',
            ['order_item_id', 'order_id', 'product_id', 'sales'],
            items_rows,
        ))
        f.write('\n')

        f.write('SET FOREIGN_KEY_CHECKS = 1;\n')

    print(f'Wrote {out_path}')


def load_into_mysql(customers, products, orders, order_items, args):
    try:
        import mysql.connector
    except ImportError:
        sys.exit('Error: mysql-connector-python not installed. '
                 'Run: pip install mysql-connector-python')

    cnx = mysql.connector.connect(
        host=args.host, user=args.user, password=args.password,
        database=args.database,
    )
    cur = cnx.cursor()
    cur.execute('SET FOREIGN_KEY_CHECKS = 0')

    cur.executemany(
        'INSERT INTO customers (customer_id, customer_name, segment) VALUES (%s, %s, %s)',
        customers[['Customer ID', 'Customer Name', 'Segment']].values.tolist(),
    )
    print(f'  Inserted {cur.rowcount} customers')

    cur.executemany(
        'INSERT INTO products (product_id, product_name, category, sub_category) '
        'VALUES (%s, %s, %s, %s)',
        products[['Product ID', 'Product Name', 'Category', 'Sub-Category']].values.tolist(),
    )
    print(f'  Inserted {cur.rowcount} products')

    orders_rows = [
        (r['Order ID'], r['Customer ID'],
         r['Order Date'].date(), r['Ship Date'].date(), r['Ship Mode'],
         r['Country'], r['City'], r['State'], r['Postal Code'],
         int(r['region_id']))
        for _, r in orders.iterrows()
    ]
    cur.executemany(
        'INSERT INTO orders (order_id, customer_id, order_date, ship_date, ship_mode, '
        'country, city, state, postal_code, region_id) '
        'VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)',
        orders_rows,
    )
    print(f'  Inserted {cur.rowcount} orders')

    items_rows = [
        (int(r['Row ID']), r['Order ID'], r['Product ID'], float(r['Sales']))
        for _, r in order_items.iterrows()
    ]
    cur.executemany(
        'INSERT INTO order_items (order_item_id, order_id, product_id, sales) '
        'VALUES (%s, %s, %s, %s)',
        items_rows,
    )
    print(f'  Inserted {cur.rowcount} order_items')

    cur.execute('SET FOREIGN_KEY_CHECKS = 1')
    cnx.commit()
    cur.close()
    cnx.close()
    print('Load complete.')


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--csv', required=True, help='Path to train.csv')
    p.add_argument('--out', default='02_data.sql', help='Output SQL file (if not --load)')
    p.add_argument('--load', action='store_true', help='Load directly into MySQL')
    p.add_argument('--host', default='localhost')
    p.add_argument('--user', default='root')
    p.add_argument('--password', default='')
    p.add_argument('--database', default='retail_analytics')
    args = p.parse_args()

    print(f'Reading {args.csv} ...')
    df = load_and_clean(Path(args.csv))
    print(f'  {len(df):,} rows loaded')

    customers = build_customers(df)
    products = build_products(df)
    orders = build_orders(df)
    order_items = build_order_items(df)

    print(f'  {len(customers):,} customers')
    print(f'  {len(products):,} products')
    print(f'  {len(orders):,} orders')
    print(f'  {len(order_items):,} order_items')

    if args.load:
        load_into_mysql(customers, products, orders, order_items, args)
    else:
        write_sql_file(customers, products, orders, order_items, Path(args.out))


if __name__ == '__main__':
    main()
